### ISSUE TITLE
What's the difference between this project and opencv aruco from functions and effects?

### ISSUE THREAD

**Issue by DozenCoder** [walchko/ar_markers#1]
I'm very interested in your ar_markers project, and it work well in my project, but I wonder what difference is between your project and [opencv aruco_detection](https://docs.opencv.org/3.4.1/d5/dae/tutorial_aruco_detection.html) from functions and effects? And your project seems not use opencv aruco at all.  
Because my project first use your ar_markers code(It works well!), but I find the opencv aruco has the almost same functions, so I have this doubt....

**Comment by walchko** [comment]
This is simpler I think. This project was for a robotics/computer vision class and I wanted it simple enough we could go through the code and they understood. I was also teaching them OpenCV, so they were getting familiar with that. I taught them the encoding (and tested them on it) and how it worked. Eventually we made "street signs" and the students drove Roomba robots around. When they detected an intersection, they used the camera to read the street sign (ar marker) and it told them to: go straight, turn left, or turn right. This is no where near as robust as other projects (I bet), it really is a teaching tool on the basics.

**Comment by DozenCoder** [comment]
@walchko Thanks for your reply! Your students must have benefited a lot from this project.

**Comment by MythicManiac** [comment]
@superPershing the OpenCV lib is probably far more robust and feature-complete (it does things beyond just ArUco markers too), as it has a longer development history and a bigger development base.

Main benefit I see this project having is it being in pure python.

**Comment by DozenCoder** [comment]
@MythicManiac Thanks for your reply!
